### ISSUE TITLE
URLs returned by this library aren't the URLs of the bookmarks

### ISSUE THREAD

**Issue by CHaskell2** [lionheart/pinboard.py#21]
Hey folks,

I feel like I might be missing something here, but it seems like all of the URL attributes returned by this library only consist of the domain name, not the actual URL of the bookmark.

This is shown in the examples in the readme, too; like this snippet:

`<Bookmark description="40 Random Letters and Numbers" url="gist.github.com">,`

Using parse_response=false shows the full URL as I'd expect.

**Comment by amkelly** [comment]
I am seeing this same behavior, are @CHaskell2 and I missing something? 

``<Bookmark description="Geothermal power - Wikipedia" url="en.wikipedia.org">,
  <Bookmark description="Enhanced geothermal system - Wikipedia" url="en.wikipedia.org">, 
   <Bookmark description="Hot dry rock geothermal energy - Wikipedia" url="en.wikipedia.org">,
``
Given that all the examples in the readme display this same behavior, and the following code:

``    def __repr__(self):
        parse_result = urllib.parse.urlparse(self.url)
        return "<Bookmark description=\"{}\" url=\"{}\">".format(self.description, parse_result.netloc)
``
I'm very much a beginning programmer, but it looks like 'parse_result.netloc' is the part of the code which returns only the netloc portion of the total bookmark URL. See urllib parse_results docs [here](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.ParseResult)

I'd guess this is a design decision so that the response object gives enough URL information to be useful without cluttering it with the whole url and assume perhaps that users wanting to interact with the whole URL will do so with a different part of the utility? Is there a way to have the response object in this part of the library return the full URLs?

Please correct any of the assumptions or errors I may have made here.
Thanks.

**Comment by dlo** [comment]
@CHaskell2 @amkelly 

> This is shown in the examples in the readme, too; like this snippet:
>
>     <Bookmark description="40 Random Letters and Numbers" url="gist.github.com">,

This is simply the object representation. The object _itself_ still contains all of the parameters that you would expect. Displaying the bookmarks in this form is purely for aesthetic reasons, but if you take this object and print `bookmark.url`, you will get the full URL back, not just the domain.

> I'd guess this is a design decision so that the response object gives enough URL information to be useful without cluttering it with the whole url and assume perhaps that users wanting to interact with the whole URL will do so with a different part of the utility?

This is exactly it. Many of the URLs will have UTM params and other mess in the query string, so we only show the most information dense part of the URL when manipulating the objects in the Python console.

Note that the `__repr__` method doesn't change anything about the object itself, only how it appears when manipulating it in the REPL.

Please let me know if this helps!

**Comment by amkelly** [comment]
Thanks so much for the library and the quick response! That helps me get a better grasp on how the different parts of the library work, I appreciate it!
