### ISSUE TITLE
Bug - Destructively silently overwrites bookmarks data

### ISSUE THREAD

**Issue by tedmiston** [lionheart/pinboard.py#32]
Using the simple `pb.posts.add(...)` method listed in the readme to add a bookmark silently overwrites (loses) existing bookmark data already in Pinboard.

This is highly unintuitive behavior vs raising an exception or including something like an explicit `allow_overwrite=True` flag.

This client's silently overwriting data caused me to lose data on a bunch of existing bookmarks :(.

**Comment by dlo** [comment]
Yikes, I'm so sorry @tedmiston. It has been a LONG time since I tested this behavior, but Pinboard's API has not had complete consistency over the years. This did not used to be the behavior. In the past, it used to be necessary to delete and re-add bookmarks to perform updates.

I'm very much open to making this non-destructive, but it will probably entail adding another method to the Pinboard class.

The current API is essentially just a wrapper over the actual API. There's no extra logic that the library performs before outgoing calls, save for formatting and a few other minor things to ensure the API call can go through successfully.
